id: P000200
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༈བློ་སྦྱོང་དོན་བདུན་མའི་ལྗངས་ཁྲིད་རྒྱལ་སྲས་ཆོས་ཀྱི་མྱུ་གུའི་ཞལ་ལུང་། །
  authors: []
  layers:
  - book_title
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: SHE-PRA-01
web_metadata:
  title:
    en: A Teaching of Bodhisattava Sapling of Dharma on the Seven-Point Mind Training
    bo: བློ་སྦྱོང་དོན་བདུན་མའི་ལྗངས་ཁྲིད་རྒྱལ་སྲས་ཆོས་ཀྱི་མྱུ་གུའི་ཞལ་ལུང་།
  collection:
    en: Shechen Practice Series–  Book 1
    bo: ཞེ་ཆེན་ཉམས་ལེན་སྐོར།–  དེབ། ༡
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-PRA-01
  category:
    en: Mind Training
    bo: བློ་སྦྱོང།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-PRA-01.epub
  description:
    en: ''
    bo: ''
